H2 resource type
sul-dlss-labs/cocina-descriptive-metadata pull request #106
Opened 2020-11-02 21:32 UTC by arcadiafalcone

**NOTE:  Person merging should ensure that any mapping changes are ticketed as a cocina mapping in dor-services-app, e.g. dor-services-app/issues/1251**

## Why was this change made?
To map H2 resource types and subtypes to COCINA and MODS

2020-11-02 22:28 UTC, ndushay reviewed
I would say go! as this is better than what we have now, but probably @jcoyne or someone more savvy about H2 types should review.

2020-11-03 14:22 UTC, jcoyne requested changes
Currenlty the h2 form supports multiple subtypes.  Can you show how we can do that here, or do we need to change the form?

2020-11-03 14:22 UTC, jcoyne commented on h2_cocina_mappings/h2_to_cocina_form.txt
> +<genre type="H2 subtype">GIS>
Looks like there's a problem with an end tag here.

2020-11-03 22:26 UTC, arcadiafalcone commented
I fixed the tag typo and added a mapping for multiple subtypes.

2020-11-03 22:33 UTC, jcoyne approved these changes

2020-11-03 22:33 UTC, merged